// Copyright (c) 2026 Tiago de Carvalho Vilas Boas.
// SPDX-License-Identifier: Apache-2.0

package nbtier

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

var tierName = map[string]int{"small": Small, "mid": Mid, "frontier": Frontier}

// Embedded training data is a frozen copy of the maintainer seed set (downshift-labs).
func TestTrainDataEmbeddedShape(t *testing.T) {
	var rows []struct{ Prompt string }
	if err := json.Unmarshal(trainJSON, &rows); err != nil {
		t.Fatal(err)
	}
	if len(rows) != 200 {
		t.Fatalf("embedded train rows = %d, want 200", len(rows))
	}
}

type goldenRow struct {
	Split  string  `json:"split"`
	I      int     `json:"i"`
	Prod   string  `json:"prod"`
	NB     string  `json:"nb"`
	Margin float64 `json:"margin"`
	Final  string  `json:"final"`
}

func loadPrompts(t *testing.T, name string) []string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", "benchmark", name))
	if err != nil {
		t.Skip("benchmark datasets live in downshift-labs; full NB parity runs there")
	}
	var rows []struct{ Prompt string }
	if err := json.Unmarshal(b, &rows); err != nil {
		t.Fatal(err)
	}
	out := make([]string, len(rows))
	for i, r := range rows {
		out[i] = r.Prompt
	}
	return out
}

// The Go port reproduces tools/baseline/nb_tier.py (label, margin and the
// upshift-only decision at the frozen T) on all 500 seed + holdout prompts.
// testdata/golden.json was generated by the Python baseline.
func TestMatchesPythonBaseline(t *testing.T) {
	b, err := os.ReadFile(filepath.Join("testdata", "golden.json"))
	if err != nil {
		t.Skip("golden parity fixtures live in downshift-labs (training/nbtier/)")
	}
	var golden []goldenRow
	if err := json.Unmarshal(b, &golden); err != nil {
		t.Fatal(err)
	}
	prompts := map[string][]string{"seed": loadPrompts(t, "tasks.json"), "holdout": loadPrompts(t, "holdout.json")}
	if len(golden) != len(prompts["seed"])+len(prompts["holdout"]) {
		t.Fatalf("golden has %d rows", len(golden))
	}
	for _, g := range golden {
		p := prompts[g.Split][g.I]
		if got := Predict(p); got != g.NB {
			t.Errorf("%s[%d] label %s, python %s", g.Split, g.I, got, g.NB)
		}
		s := Suggest(p, tierName[g.Prod])
		final := s.From
		if s.Upshift {
			final = s.To
		}
		if final != tierName[g.Final] {
			t.Errorf("%s[%d] final tier %d, python %s", g.Split, g.I, final, g.Final)
		}
		if math.Abs(s.Margin-g.Margin) > 1e-9 {
			t.Errorf("%s[%d] margin %.12f, python %.12f", g.Split, g.I, s.Margin, g.Margin)
		}
	}
}

// Suggest never proposes a tier below the production tier.
func TestSuggestNeverLowers(t *testing.T) {
	for _, p := range append(loadPrompts(t, "tasks.json"), loadPrompts(t, "holdout.json")...) {
		for tier := Small; tier <= Frontier; tier++ {
			s := Suggest(p, tier)
			if s.To < tier || (s.Upshift && s.To <= tier) {
				t.Fatalf("Suggest(%q, %d) = %+v", p, tier, s)
			}
		}
	}
}

func TestNoKnownFeatureIsSafe(t *testing.T) {
	s := Suggest("zzqx", Small)
	if s.Upshift || math.IsNaN(s.Margin) || math.IsInf(s.Margin, 0) {
		t.Fatalf("unknown-vocabulary prompt: %+v", s)
	}
}

// Trivial reproduces the Python TRIVIAL-downshift opinion (label TRIVIAL and
// small-vs-rest margin >= 0.2) on all 500 seed + holdout prompts.
func TestTrivialMatchesPython(t *testing.T) {
	b, err := os.ReadFile(filepath.Join("testdata", "trivial_golden.json"))
	if err != nil {
		t.Skip("trivial golden fixtures live in downshift-labs (training/nbtier/)")
	}
	var golden []struct {
		Split   string  `json:"split"`
		I       int     `json:"i"`
		Trivial bool    `json:"trivial"`
		Margin  float64 `json:"margin"`
	}
	if err := json.Unmarshal(b, &golden); err != nil {
		t.Fatal(err)
	}
	prompts := map[string][]string{"seed": loadPrompts(t, "tasks.json"), "holdout": loadPrompts(t, "holdout.json")}
	for _, g := range golden {
		ok, m := Trivial(prompts[g.Split][g.I])
		if ok != g.Trivial || math.Abs(m-g.Margin) > 1e-9 {
			t.Errorf("%s[%d] Trivial=%v margin %.12f, python %v %.12f", g.Split, g.I, ok, m, g.Trivial, g.Margin)
		}
	}
}
