// Copyright (c) 2026 Tiago de Carvalho Vilas Boas.
// SPDX-License-Identifier: Apache-2.0

package outcome

import (
	"fmt"
	"io"
	"math"
	"strings"

	"github.com/tiagovilasboas/downshift/internal/benchmark"
	"github.com/tiagovilasboas/downshift/internal/core"
)

// README markers delimiting the generated block.
const (
	BeginMarker = "<!-- downshift-report:begin -->"
	EndMarker   = "<!-- downshift-report:end -->"
)

// Dataset is a classifier benchmark file shown in the report.
type Dataset struct{ Path, Name string }

// Route maps a prompt to the tier the production classifier picks.
func Route(prompt string) core.Tier { return core.ClassifyWithSemantic(prompt).Complexity.Tier() }

// Report renders the generated README block: classifier benchmark numbers for
// each dataset and outcome-eval pass rates from recorded runs. It never makes
// a model call; without recorded runs it says pass rates are not measured.
func Report(datasets []Dataset, tasks []Task, runs []Run) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n<!-- Generated by `downshift eval-outcome --report` (maintainer). Public metrics: benchmark/REPORT.md -->\n\n", BeginMarker)
	if len(datasets) == 0 {
		b.WriteString("**Classifier benchmark:** datasets are maintained in downshift-labs. " +
			"Published figures: `benchmark/REPORT.md`.\n\n")
	} else {
		b.WriteString("**Classifier benchmark** (default classifier; labels are a human complexity rubric, not measured outcomes):\n\n")
		b.WriteString("| Dataset | Tasks | Tier accuracy (95% CI) | FRONTIER→MID | FRONTIER→SMALL | SMALL→MID | SMALL→FRONTIER |\n|---|---|---|---|---|---|---|\n")
	}
	for _, d := range datasets {
		ts, err := benchmark.LoadDataset(d.Path)
		if err != nil {
			return "", err
		}
		res := benchmark.Run(ts, io.Discard)
		rep := benchmark.GenerateReport(res)
		fMid, fSmall, cfMid, cfSmall, fTot := benchmark.UnsafeDowngradeRates(res)
		sMid, sFr, csMid, csFr, sTot := benchmark.WastefulOverRoutingRates(res)
		fmt.Fprintf(&b, "| %s | %d | %.1f%% (%.1f–%.1f%%) | %s | %s | %s | %s |\n", d.Name, rep.TotalTasks,
			rep.TierAccuracy*100, rep.TierAccuracyCI95.Low*100, rep.TierAccuracyCI95.High*100,
			frac(fMid, cfMid, fTot), frac(fSmall, cfSmall, fTot), frac(sMid, csMid, sTot), frac(sFr, csFr, sTot))
	}

	routed := map[string]core.Tier{}
	perTier := map[core.Tier]int{}
	complexBelow, complexN := 0, 0
	for _, t := range tasks {
		routed[t.ID] = Route(t.Prompt)
		perTier[routed[t.ID]]++
		if t.Label == "COMPLEX" {
			complexN++
			if routed[t.ID] != core.TierFrontier {
				complexBelow++
			}
		}
	}
	fmt.Fprintf(&b, "\n**Outcome eval** (%d Go tasks in maintainer suite; each has an executable check). "+
		"The router sends %d tasks to small, %d to mid and %d to frontier; %d of %d COMPLEX-labelled tasks are routed below frontier.\n\n",
		len(tasks), perTier[core.TierSmall], perTier[core.TierMid], perTier[core.TierFrontier], complexBelow, complexN)
	if len(runs) == 0 {
		b.WriteString("No recorded model runs in this checkout, so small-vs-frontier pass rates are **not measured**. " +
			"Record runs from downshift-labs (see `eval/outcomes/README.md`).\n")
		return b.String() + EndMarker + "\n", nil
	}
	subsets := []struct {
		name string
		in   func(Task) bool
	}{
		{"all tasks", func(Task) bool { return true }},
		{"TRIVIAL+SIMPLE labels", func(t Task) bool { return t.Label == "TRIVIAL" || t.Label == "SIMPLE" }},
		{"routed to small", func(t Task) bool { return routed[t.ID] == core.TierSmall }},
	}
	b.WriteString("| Run tier | Model | Date |")
	for _, sub := range subsets {
		fmt.Fprintf(&b, " Pass, %s (95%% CI) |", sub.name)
	}
	b.WriteString("\n|---|---|---|---|---|---|\n")
	rates := map[string]map[string]float64{} // subset -> run tier -> pass rate
	for _, r := range runs {
		fmt.Fprintf(&b, "| %s | `%s` | %s |", r.Tier, r.Model, r.Date)
		for _, sub := range subsets {
			k, n, want := 0, 0, 0
			for _, t := range tasks {
				if !sub.in(t) {
					continue
				}
				want++
				if pass, ok := r.Results[t.ID]; ok {
					n++
					if pass {
						k++
					}
				}
			}
			if n == want && n > 0 {
				if rates[sub.name] == nil {
					rates[sub.name] = map[string]float64{}
				}
				rates[sub.name][r.Tier] = float64(k) / float64(n)
			}
			fmt.Fprintf(&b, " %s |", wilsonCell(k, n))
		}
		b.WriteString("\n")
	}
	for _, sub := range subsets[1:] {
		s, okS := rates[sub.name]["small"]
		f, okF := rates[sub.name]["frontier"]
		if okS && okF {
			fmt.Fprintf(&b, "\nSmall minus frontier pass rate, %s: %+.1fpp (revisit the downshift below −5pp).\n", sub.name, (s-f)*100)
		}
	}
	return b.String() + EndMarker + "\n", nil
}

func frac(rate float64, n, total int) string {
	return fmt.Sprintf("%.1f%% (%d/%d)", rate*100, n, total)
}

func wilsonCell(k, n int) string {
	if n == 0 {
		return "n/a"
	}
	lo, hi := Wilson(k, n)
	return fmt.Sprintf("%d/%d = %.1f%% (%.1f–%.1f%%)", k, n, float64(k)/float64(n)*100, lo*100, hi*100)
}

// Wilson returns the 95% Wilson score interval for k successes out of n.
func Wilson(k, n int) (float64, float64) {
	if n == 0 {
		return 0, 0
	}
	const z = 1.959963984540054
	p, nf := float64(k)/float64(n), float64(n)
	den := 1 + z*z/nf
	mid := (p + z*z/(2*nf)) / den
	half := z * math.Sqrt(p*(1-p)/nf+z*z/(4*nf*nf)) / den
	return math.Max(0, mid-half), math.Min(1, mid+half)
}

// Splice replaces the marked block in doc with block (which carries its own markers).
func Splice(doc, block string) (string, error) {
	i := strings.Index(doc, BeginMarker)
	j := strings.Index(doc, EndMarker)
	if i < 0 || j < i {
		return "", fmt.Errorf("markers %s ... %s not found", BeginMarker, EndMarker)
	}
	end := j + len(EndMarker)
	if end < len(doc) && doc[end] == '\n' {
		end++
	}
	return doc[:i] + block + doc[end:], nil
}
