// Copyright (c) 2026 Tiago de Carvalho Vilas Boas.
// SPDX-License-Identifier: Apache-2.0

package core_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/tiagovilasboas/downshift/internal/core"
)

type nbGolden struct {
	Prompt, Gold string
	Prod, Final  string // production tier on main, upshift-only tier at T=0.10
}

// loadNBGolden joins internal/nbtier/testdata/golden.json (generated by the
// Python baseline from main's production tiers) with the seed and holdout
// prompts and gold labels.
func loadNBGolden(t *testing.T) []nbGolden {
	t.Helper()
	read := func(path string, v any) {
		b, err := os.ReadFile(path)
		if err != nil {
			t.Skip("NB golden fixtures and benchmark prompts live in downshift-labs")
		}
		if err := json.Unmarshal(b, v); err != nil {
			t.Fatal(err)
		}
	}
	var rows []struct {
		Split, Prod, Final string
		I                  int
	}
	read(filepath.Join("..", "nbtier", "testdata", "golden.json"), &rows)
	sets := map[string][]struct{ Prompt, Label string }{}
	for split, file := range map[string]string{"seed": "tasks.json", "holdout": "holdout.json"} {
		var s []struct{ Prompt, Label string }
		read(filepath.Join("..", "..", "benchmark", file), &s)
		sets[split] = s
	}
	out := make([]nbGolden, len(rows))
	for i, r := range rows {
		p := sets[r.Split][r.I]
		out[i] = nbGolden{p.Prompt, p.Label, r.Prod, r.Final}
	}
	return out
}

func offlineRouting(t *testing.T) {
	t.Setenv("DOWNSHIFT_GRAPHIFY_CMD", "")
}

// Flag OFF (default): every seed/holdout tier is identical to main, and the
// would-be upshift is still recorded in shadow mode.
func TestNBUpshift_OffKeepsRoutingAndRecordsShadow(t *testing.T) {
	offlineRouting(t)
	t.Setenv(core.NBUpshiftEnv, "")
	shadow := 0
	for _, g := range loadNBGolden(t) {
		d := core.Route(g.Prompt, "claude-code", "claude-opus-5-5", cat)
		if d.Tier.String() != g.Prod {
			t.Errorf("flag off changed routing: tier %s, main %s for %q", d.Tier, g.Prod, g.Prompt)
		}
		if d.NBUpshift.Applied {
			t.Errorf("flag off applied an upshift for %q", g.Prompt)
		}
		if want := g.Final != g.Prod; d.NBUpshift.Would != want {
			t.Errorf("shadow would=%v, want %v for %q", d.NBUpshift.Would, want, g.Prompt)
		}
		if d.NBUpshift.Would {
			shadow++
			if d.NBUpshift.From.String() != g.Prod || d.NBUpshift.To.String() != g.Final || d.NBUpshift.Margin < 0.10 {
				t.Errorf("shadow record %+v for %q", d.NBUpshift, g.Prompt)
			}
		}
	}
	if shadow != 10 { // 10 upshifts of 500 at the frozen T (docs/design/router-generalization.md)
		t.Errorf("shadow upshifts = %d, want 10", shadow)
	}
}

// Flag ON: the upshift is applied, never a downshift, and no frontier task
// is routed to small.
func TestNBUpshift_OnAppliesUpshiftOnly(t *testing.T) {
	offlineRouting(t)
	t.Setenv(core.NBUpshiftEnv, "1")
	tier := map[string]int{"small": 0, "mid": 1, "frontier": 2}
	applied := 0
	for _, g := range loadNBGolden(t) {
		d := core.Route(g.Prompt, "claude-code", "claude-haiku-4-5", cat)
		if d.Tier.String() != g.Final {
			t.Errorf("flag on: tier %s, want %s for %q", d.Tier, g.Final, g.Prompt)
		}
		if tier[d.Tier.String()] < tier[g.Prod] {
			t.Errorf("flag on lowered %s -> %s for %q", g.Prod, d.Tier, g.Prompt)
		}
		if g.Gold == "COMPLEX" && d.Tier == core.TierSmall {
			t.Errorf("FRONTIER->SMALL for %q", g.Prompt)
		}
		if d.NBUpshift.Applied {
			applied++
			if d.Verdict == core.VerdictUpshift && !d.ShouldRewriteModel() {
				t.Errorf("applied NB upshift was not rewritten for %q", g.Prompt)
			}
		}
	}
	if applied != 10 {
		t.Errorf("applied upshifts = %d, want 10", applied)
	}
}
